import { Dimensions, Platform, StyleSheet } from "react-native";
import { COLORS } from "../../Utils/Colors";
import { scale } from "../../Utils/Helper/Scalling";
import { FONTS } from "../../Utils/Fonts";

const styles = StyleSheet.create({
  media_file: {
    height: Dimensions.get("screen").height / 2.3,
    width: Dimensions.get("screen").width / 1.12,
    backgroundColor: COLORS.RED,
    alignSelf: "center",
    marginTop: scale(30),
    borderRadius: scale(10),
  },
  linearView: {
    height: Dimensions.get("screen").height / 2.3,
    width: Dimensions.get("screen").width / 1.12,
    borderRadius: scale(10),
    justifyContent: "flex-end",
    alignItems: "center",
  },
  eventTitle: {
    fontSize: scale(22),
    fontFamily: FONTS.POPPINS_MEDIUM,
    color: COLORS.WHITE,
    marginBottom: scale(35),
    textAlign: "center",
  },
  venueText: {
    alignSelf: "center",
    fontSize: scale(17),
    color: COLORS.WHITE,
    fontFamily: FONTS.POPPINS_MEDIUM,
    marginTop: scale(15),
  },
  guestAllowedText: {
    alignSelf: "center",
    fontSize: scale(14),
    color: COLORS.BLACK,
    fontFamily: FONTS.POPPINS_MEDIUM,
    textTransform: "capitalize",
  },
  iconContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    marginHorizontal: scale(15),
  },
  iconImage: { height: scale(20), width: scale(20), tintColor: COLORS.RED },
  keyFeatureTitle: {
    textAlign: "left",
    marginLeft: scale(15),
    fontSize: scale(11),
    fontFamily: FONTS.POPPINS_MEDIUM,
    color: COLORS.BLACK,
    width: Dimensions.get("screen").width / 1.5,
  },
  aboutThisText: {
    alignSelf: "center",
    fontSize: scale(20),
    color: COLORS.BLACK,
    fontFamily: FONTS.PLAYFAIR_DISPLAY_REGULAR,
    marginTop: scale(25),
  },
  desStyles: {
    marginHorizontal: scale(35),
    alignSelf: "center",
    color: COLORS.WHITE,
    fontFamily: FONTS.POPPINS_REGULAR,
    fontSize: scale(10.5),
    marginTop: scale(5),
  },
  saveText: {
    fontSize: scale(17),
    color: COLORS.WHITE,
    fontFamily: FONTS.POPPINS_REGULAR,
  },
  submitButton: {
    height: Dimensions.get("screen").height / 15,
    width: Dimensions.get("screen").width / 1.12,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.RED,
    borderRadius: scale(10),
    alignSelf: "center",
  },
  modalsubmitButton: {
    height: Dimensions.get("screen").height / 16,
    width: Dimensions.get("screen").width / 1.18,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.RED,
    borderRadius: scale(10),
    alignSelf: "center",
  },
  modalClasssubmitButton: {
    height: Dimensions.get("screen").height / 16,
    width: Dimensions.get("screen").width / 1.2,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.RED,
    borderRadius: scale(10),
    alignSelf: "center",
  },
  footerContainer: {
    position: "relative",
    height: scale(80),
    justifyContent: "center",
    alignItems: "center",
  },
  keyContainer: {
    backgroundColor: COLORS.WHITE,
    alignSelf: "center",
    width: Dimensions.get("screen").width / 1.12,
    marginTop: scale(20),
    paddingVertical: scale(15),
    borderRadius: scale(8),
    marginHorizontal: scale(10),
  },
  modalContainer: {
    flex: 1,
    backgroundColor: COLORS.BACKGROUND_COLOR,
    paddingHorizontal: scale(15),
    justifyContent: "center",
  },
  modalClassContainer: {
    flex: 1,
    backgroundColor: COLORS.BACKGROUND_COLOR,
    paddingHorizontal: scale(20),
    justifyContent: "center",
  },
  subModalContainer: {
    backgroundColor: COLORS.WHITE,
    borderRadius: scale(10),
    paddingVertical: scale(10),
  },
  subModalContainer2: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: scale(10),
  },
  titleContainer: { flex: scale(8), alignItems: "center" },
  titleModalText: {
    fontSize: scale(19),
    color: COLORS.BLACK,
    fontFamily: FONTS.PLAYFAIR_DISPLAY_MEDIUM,
    // marginLeft: scale(20),
  },
  titleClassModalText: {
    fontSize: scale(18),
    color: COLORS.BLACK,
    fontFamily: FONTS.PLAYFAIR_DISPLAY_MEDIUM,
    marginHorizontal: scale(20),
    marginTop: scale(10),
  },
  closeContainer: { flex: 2, justifyContent: "center" },
  closeImg: {
    height: scale(30),
    width: scale(30),
    alignSelf: "flex-end",
    tintColor: COLORS.RED,
  },
  personContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: scale(20),
    marginTop: scale(35),
  },
  personSubContainer: { flex: 6, alignItems: "center" },
  memberHeadText: {
    fontSize: scale(13),
    color: COLORS.BLACK,
    fontFamily: FONTS.POPPINS_MEDIUM,
  },
  memberPerPersonText: {
    fontSize: scale(10),
    color: COLORS.BLACK,
    fontFamily: FONTS.POPPINS_REGULAR,
  },
  counterContainer: {
    flexDirection: "row",
    borderWidth: 1,
    justifyContent: "space-between",
    alignItems: "center",
    borderRadius: scale(10),
    marginTop: scale(15),
  },
  minusContainer: {
    height: scale(30),
    width: scale(35),
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: scale(10),
    borderRightWidth: scale(0.7),
  },
  minusText: {
    height: scale(12),
    width: scale(12),
    tintColor: COLORS.RED,
  },
  countText: {
    paddingHorizontal: scale(10),
    fontSize: scale(14),
    color: COLORS.BLACK,
    fontFamily: FONTS.POPPINS_REGULAR,
    textAlign: "center",
    lineHeight: scale(20),
  },
  plusCntainer: {
    height: scale(30),
    width: scale(35),
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: scale(10),
    borderLeftWidth: scale(0.7),
  },
  descInput: {
    height: Dimensions.get("screen").height / 18,
    width: Dimensions.get("screen").width / 1.3,
    borderRadius: scale(5),
    borderWidth: scale(0.6),
    marginTop: scale(45),
    borderColor: COLORS.RED,
    alignSelf: "center",
  },
  inputContainer: {
    marginTop: scale(30),
    marginHorizontal: scale(25),
  },
  descStyle: {
    marginTop: scale(-10),
    backgroundColor: COLORS.WHITE,
    width: Dimensions.get("window").width / 3.5,
    textAlign: "center",
    fontSize: Platform.OS === "ios" ? scale(12) : scale(13),
    fontFamily: FONTS.POPPINS_MEDIUM,
    marginLeft: scale(7),
    color: COLORS.RED,
  },
  descinputContainer: {
    alignItems: "baseline",
    justifyContent: "center",
    fontSize: scale(13),
    fontFamily: FONTS.POPPINS_MEDIUM,
    color: COLORS.BLACK,
    paddingLeft: scale(10),
    paddingVertical: Platform.OS === "ios" ? scale(5) : scale(0),
  },
  MenuchoicesView: {
    alignItems: "center",
    flexDirection: "row",
  },
  whereradioView: {
    borderWidth: 1,
    height: scale(20),
    width: scale(20),
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 20,
  },
  radioinnerView: {
    backgroundColor: COLORS.LIGHT_ORANGE,
    height: scale(13),
    width: scale(13),
    borderRadius: 10,
  },
  radioLabel: {
    marginLeft: scale(18),
    fontSize: scale(12),
    fontFamily: FONTS.POPPINS_MEDIUM,
    color: COLORS.BLACK,
  },
  totalContainer: {
    borderTopWidth: scale(0.8),
    borderColor: COLORS.BLACK,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: scale(15),
    paddingHorizontal: scale(5),
    paddingVertical: scale(20),
  },
  totalAmountText: {
    fontSize: scale(12),
    color: COLORS.BLACK,
    fontFamily: FONTS.POPPINS_MEDIUM,
  },
  totalAmountVal: {
    fontSize: scale(12),
    color: COLORS.BLACK,
    fontFamily: FONTS.POPPINS_REGULAR,
    marginRight: scale(20),
  },
  aboutContainer: {
    marginLeft: scale(25),
    backgroundColor: "#FFEECA",
    width: Dimensions.get("screen").width / 1.15,
    borderRadius: scale(10),
    marginTop: scale(25),
    marginVertical: scale(20),
  },
  aboutImageContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-start",
    marginTop: scale(15),
  },
  aboutImage: {
    height: scale(40),
    width: scale(40),
    marginHorizontal: scale(10),
    backgroundColor: "red",
    borderRadius: scale(30),
  },
  aboutDescContainer: { flexDirection: "column", flex: 8 },
  aboutName: {
    fontSize: scale(12),
    fontFamily: FONTS.POPPINS_MEDIUM,
    color: COLORS.BLACK,
  },
  aboutDetail: {
    fontSize: scale(10),
    fontFamily: FONTS.POPPINS_REGULAR,
    color: COLORS.BLACK,
    marginTop: scale(3),
  },
  TodaychoicesView: {
    alignItems: "center",
    flexDirection: "row",
    marginTop: scale(20),
    // marginRight: scale(20),
  },
});
export default styles;
