import { Dimensions, StyleSheet } from "react-native";
import { scale } from "../../Utils/Helper/Scalling";
import { COLORS } from "../../Utils/Colors";
import { FONTS } from "../../Utils/Fonts";

const styles = StyleSheet.create({
  container: { flex: scale(1), backgroundColor: COLORS.WHITE },
  headerText: { fontSize: scale(20), right: scale(30), fontFamily: "Inter" },
  mainContainer: {
    marginVertical: scale(10),
    headerText: { fontSize: scale(20), right: scale(30) },
    width: Dimensions.get("screen").width / 1.16,
    borderWidth: scale(1),
    borderRadius: scale(10),
    marginHorizontal: scale(25),
  },
  subContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginVertical: scale(10),
  },
  headingText: {
    fontSize: scale(20),
    fontWeight: "600",
    lineHeight: scale(20),
    fontFamily: FONTS.POPPINS_REGULAR,
  },
  headingPdfImage: {
    height: scale(25),
    width: scale(25),
  },
  pdfImage: {
    marginHorizontal: scale(50),
    left: scale(40),
    marginVertical: scale(10),
  },
  billSubText: {
    marginVertical: 7,
    fontSize: scale(12),
    fontFamily: FONTS.POPPINS_REGULAR,
  },
  billContainer: { flexDirection: "row", marginVertical: scale(10) },
  billDateContainer: { flexDirection: "column", marginHorizontal: scale(25) },
  billDateText: {
    fontSize: scale(13),
    fontFamily: FONTS.POPPINS_MEDIUM,
  },
  billPeriodContainer: { flexDirection: "column" },
  amountContainer: { flexDirection: "column" },
  statusContainer: { flexDirection: "column", marginHorizontal: scale(25) },
  makeAmount: {
    height: scale(35),
    width: scale(102),
    backgroundColor: COLORS.BLACK,
    marginVertical: scale(10),
    justifyContent: "center",
    alignItems: "center",
    borderRadius: scale(10),
  },
  raiseIssueImage: {
    height: scale(15),
    width: scale(15),
    transform: [{ rotate: "180deg" }],
    top: scale(2),
  },
  raiseIssueButton: {
    flexDirection: "row",
    marginHorizontal: scale(40),
    left: scale(35),
  },
  raiseIssueText: {
    fontSize: scale(13),
    fontFamily: FONTS.POPPINS_REGULAR,
  },
  makePaymentcontainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  submitText: {
    color: COLORS.WHITE,
    lineHeight: scale(40),
    fontSize: scale(16),
    fontFamily: FONTS.POPPINS_REGULAR,
  },
  raiseSubmitText: {
    color: COLORS.RED,
    lineHeight: scale(40),
    fontSize: scale(16),
    fontFamily: FONTS.POPPINS_REGULAR,
  },
  billBoxContainer: {
    width: Dimensions.get("screen").width / 1.17,
    marginHorizontal: scale(25),
    marginVertical: scale(20),
    borderRadius: scale(12),
    backgroundColor: "#f5f5f5",
  },
  billBoxSubContainer: {
    height: scale(25),
    width: scale(70),
    backgroundColor: COLORS.ORANGE,
    alignSelf: "flex-end",
    borderRadius: scale(10),
    // borderTopRightRadius: scale(12),
    // borderBottomLeftRadius: scale(10),
    justifyContent: "center",
    alignItems: "center",
    marginRight: scale(10),
    marginTop: scale(10),
  },
  prndingTxt: {
    fontSize: scale(11.5),
    fontFamily: FONTS.POPPINS_REGULAR,
    color: COLORS.WHITE,
    textAlign: "center",
    lineHeight: scale(25)
  },
  billHeadingText: {
    marginVertical: scale(10),
    borderBottomWidth: scale(0.7),
    borderBottomColor: COLORS.BLACK,
  },
  raiseIssueTextButton: {
    height: Dimensions.get("screen").height / 16,
    width: Dimensions.get("screen").width / 2.6,
    borderRadius: scale(5),
    borderWidth: scale(0.7),
    borderColor: COLORS.BLACK,
    justifyContent: "center",
    alignItems: "center",
  },
  MakePaymentButton: {
    width: Dimensions.get("screen").width / 2.57,
    height: Dimensions.get("screen").height / 17,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: scale(10),
    marginHorizontal: scale(15),
  },
  billingButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: scale(30),
    marginHorizontal: scale(12),
  },
  downloadBillstyle: {
    alignItems: "center",
    borderRadius: scale(10),
    paddingHorizontal: scale(15),
    width: Dimensions.get("screen").width / 2.57,
    height: Dimensions.get("screen").height / 17,
    justifyContent: "center",
    backgroundColor: COLORS.BLACK,
    marginRight:scale(5)
  },
  downloadBillText: {
    color: COLORS.WHITE,
    fontSize: scale(13),
    fontFamily: FONTS.POPPINS_REGULAR,
    marginLeft: scale(3),
  },
  payBillText: {
    fontSize: scale(12),
    fontFamily: FONTS.POPPINS_REGULAR,
  },
  pdfIcon: {
    height: scale(16),
    width: scale(16),
    tintColor: COLORS.WHITE,
    marginRight: scale(5),
  },
  headingModalText: {
    flexDirection: "row",
    marginHorizontal: scale(10),
    alignSelf: "center",
  },
  raiseText: {
    fontFamily: FONTS.POPPINS_MEDIUM,
    fontSize: scale(12),
    color: COLORS.BLACK,
    // marginHorizontal: scale(10),
  },
  raiseIssueMainText: {
    fontSize: scale(11),
    fontFamily: FONTS.POPPINS_MEDIUM,
    color: COLORS.RED,
    textDecorationLine: "underline",
  },
  lastModalContainer: {
    backgroundColor: COLORS.WHITE,
    alignItems: "baseline",
    width: Dimensions.get("screen").width / 1.10,
    alignSelf: "center",
    marginTop: scale(25),
    borderRadius: scale(10),
  },
  welcomeText: {
    fontSize: scale(20),
    color: COLORS.BLACK,
    fontFamily: FONTS.PLAYFAIR_DISPLAY_MEDIUM,
    alignSelf: "center",
  },
  billsText: {
    fontSize: scale(15),
    color: COLORS.RED,
    fontFamily: FONTS.POPPINS_MEDIUM,
    alignSelf: "center",
    marginTop: scale(10),
  },
  billRenderItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: scale(25),
    marginTop: scale(10),
  },
  renderKey: {
    fontSize: scale(13),
    color: COLORS.BLACK,
    fontFamily: FONTS.POPPINS_REGULAR,
  },
  renderView: {
    fontSize: scale(13),
    color: COLORS.BLACK,
    fontFamily: FONTS.POPPINS_MEDIUM,
  },
  raiseButton: {
    marginVertical: scale(20),
    marginHorizontal: scale(20),
    alignSelf: "center",
  },
  flatContentContainer: {
    // marginHorizontal: scale(5),
    paddingBottom: scale(25),
    marginTop:scale(20)
  },
  //   billingContainer: {
  //     flexDirection: "column",
  //     justifyContent: "space-between",
  //     alignItems: "center",
  //     width: Dimensions.get("screen").width / 3.1,
  //     marginTop: scale(20),
  //   },
  //   backgroundContainer: {
  //     height: scale(65),
  //     width: scale(65),
  //     borderRadius: scale(40),
  //     backgroundColor: "rgba(46, 77, 133, 0.1)",
  //     justifyContent: "center",
  //     alignItems: "center",
  //   },
  //   billingTextView: {
  //     width: Dimensions.get("screen").width / 5,
  //     justifyContent: "center",
  //     alignItems: "center",
  //   },
  boxText: {
    fontSize: scale(12),
    fontFamily: FONTS.POPPINS_MEDIUM,
    marginTop: scale(10),
    textAlign: "center",
  },
  desText: {
    fontSize: scale(12),
    fontFamily: FONTS.POPPINS_MEDIUM,
    textAlign: "center",
  },
  listRenderContainer: {
    backgroundColor: COLORS.WHITE,
    height: scale(95),
    width: scale(95),
    marginHorizontal: scale(8),
    marginTop: scale(22),
    justifyContent: "center",
    alignItems: "center",
    borderRadius: scale(10),
  },
});
export default styles;
