import { StyleSheet, Dimensions, Platform } from "react-native";
import { scale } from "../../Utils/Helper/Scalling";
import { COLORS } from "../../Utils/Colors";
import { FONTS } from "../../Utils/Fonts";

const styles = StyleSheet.create({
  mainContainer: { flex: 1, backgroundColor: COLORS.ORANGE },
  contentcontainer: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: scale(10),
    marginTop: scale(10),
    justifyContent: "space-between",
  },
  nameSkeleton: {
    height: scale(8),
    width: scale(160),
    borderRadius: scale(10),
  },
  nameSubSkeleton: {
    height: scale(8),
    width: scale(100),
    borderRadius: scale(10),
    marginTop: scale(10),
  },
  headTextSkeleton: {
    height: scale(10),
    width: scale(130),
    borderRadius: scale(10),
    marginTop: scale(10),
  },
  arrowSkeleton: {
    height: scale(10),
    width: scale(60),
    borderRadius: scale(10),
    marginTop: scale(10),
  },
  eventViewSkeleton: {
    height: Dimensions.get("screen").height / 2,
    width: Dimensions.get("screen").width / 1.3,
    justifyContent: "flex-end",
    borderRadius: scale(20),
    marginTop: scale(20),
  },
  event2ViewSkeleton: {
    height: Dimensions.get("screen").height / 2,
    width: Dimensions.get("screen").width / 1.3,
    justifyContent: "flex-end",
    borderRadius: scale(20),
    marginTop: scale(20),
    marginLeft: scale(15),
  },
  classHedContainer: {
    height: scale(10),
    width: scale(130),
    borderRadius: scale(10),
    marginTop: scale(10),
  },
  classSubHeadTextSkeleton: {
    height: scale(10),
    width: scale(80),
    borderRadius: scale(10),
    marginTop: scale(10),
  },
  classViewconteinSkeleton: {
    borderRadius: scale(10),
    marginTop: scale(20),
    width: Dimensions.get("screen").width / 2,
    height: Dimensions.get("screen").height / 7.5,
  },
  classViewconteinSkeleton2: {
    borderRadius: scale(10),
    marginTop: scale(20),
    marginLeft: scale(15),
    width: Dimensions.get("screen").width / 2,
    height: Dimensions.get("screen").height / 7.5,
  },
  bannerSkeleton: {
    marginTop: scale(30),
    marginBottom: scale(25),
    height: Dimensions.get("screen").height / 3.7,
    width: Dimensions.get("screen").width / 1.11,
    alignSelf: "center",
    borderRadius: scale(10),
  },
  userIcon: { height: scale(45), width: scale(45), borderRadius: scale(50) },
  nameContainer: {
    flex: scale(9),
    flexDirection: "column",
    justifyContent: "center",
    paddingLeft: scale(10),
  },
  headingText: {
    fontSize: scale(18),
    fontFamily: FONTS.PLAYFAIR_DISPLAY_REGULAR,
    textTransform: "capitalize",
    color: COLORS.BLACK,
  },
  greetMessage: {
    fontSize: scale(12),
    fontFamily: FONTS.POPPINS_REGULAR,
    color: COLORS.WHITE,
    marginTop: scale(1),
  },
  qrContainer: {
    flex: scale(1),
    flexDirection: "column",
    alignItems: "center",
    alignSelf: "center",
  },
  qrIcon: {
    height: scale(35),
    width: scale(35),
    marginRight: scale(20),
  },
  subContentContainer: { marginTop: scale(25) },
  classesRowView: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: scale(20),
  },
  contentHeading: {
    fontSize: scale(17),
    color: COLORS.BLACK,
    fontStyle: "normal",
    fontFamily: FONTS.PLAYFAIR_DISPLAY_MEDIUM,
  },
  eventImage: {
    height: Dimensions.get("screen").height / 2,
    width: Dimensions.get("screen").width / 1.3,
  },
  linearView: {
    height: Dimensions.get("screen").height / 2,
    width: Dimensions.get("screen").width / 1.3,
    justifyContent: "flex-end",
    paddingHorizontal: scale(30),
    paddingBottom: scale(25),
    borderRadius: scale(10),
  },
  eventTitle: {
    marginTop: scale(10),
    fontFamily: FONTS.POPPINS_MEDIUM,
    fontSize: scale(20),
    color: COLORS.WHITE,
    width: Dimensions.get("screen").width / 1.5,
  },
  eventtime: {
    backgroundColor: COLORS.WHITE,
    alignItems: "baseline",
    borderRadius: scale(15),
    paddingVertical: scale(3),
    paddingHorizontal: scale(15),
    justifyContent: "center",
    alignSelf: "baseline",
  },
  eventCategoryTitle: {
    marginTop: scale(5),
    fontFamily: FONTS.POPPINS_REGULAR,
    fontSize: scale(11),
    lineHeight: scale(20),
    color: COLORS.BLACK,
  },
  startTimeText: {
    fontSize: scale(11.5),
    fontFamily: FONTS.POPPINS_MEDIUM,
    color: COLORS.BLACK,
    textAlign: "center",
    marginTop: scale(2),
  },
  TimeText: {
    fontSize: scale(12),
    fontFamily: FONTS.POPPINS_REGULAR,
    color: COLORS.ORANGE,
    marginTop: scale(3),
  },
  newsMainContainer: {
    borderRadius: scale(10),
    backgroundColor: COLORS.WHITE,
    paddingHorizontal: scale(10),
    paddingVertical: scale(15),
    width: Dimensions.get("screen").width / 2.25,
  },
  newsSubContainer: {
    borderRadius: scale(10),
    alignSelf: "baseline",
    paddingHorizontal: scale(15),
    backgroundColor: COLORS.RED,
    alignItems: "center",
    justifyContent: "center",
    height: scale(22),
  },
  newsHeadText: {
    fontFamily: FONTS.POPPINS_MEDIUM,
    fontSize: scale(9.5),
    color: COLORS.WHITE,
    lineHeight: scale(20),
    // borderWidth:scale(1),
    textAlign: "center",
    alignSelf: "baseline",
  },
  newsDesc: {
    fontSize: scale(12.5),
    fontFamily: FONTS.POPPINS_MEDIUM,
    color: COLORS.BLACK,
    marginTop: scale(5),
    marginHorizontal: scale(5),
    paddingRight: scale(20),
    width: Dimensions.get("screen").width / 2.35,
  },
  newsDate: {
    paddingTop: scale(2),
    fontFamily: FONTS.POPPINS_REGULAR,
    fontSize: scale(10.5),
    color: "#2E4D85",
    marginHorizontal: scale(6),
    paddingRight: scale(10),
    marginBottom: scale(5),
  },
  nextImage: {
    height: scale(17),
    width: scale(17),
    transform: [{ rotate: "180deg" }],
    marginLeft: scale(10),
  },
  nextIcon: { height: scale(25), width: scale(25), tintColor: COLORS.RED },
  eventContainer: {
    marginLeft: scale(15),
    paddingRight: scale(45),
    marginTop: scale(20),
  },
  emptyContainer: {
    fontSize: scale(15),
    fontFamily: FONTS.POPPINS_MEDIUM,
    color: COLORS.BLACK,
  },
  classimage: {
    height: scale(80),
    width: scale(80),
  },
  viewAllclassimage: {
    height: scale(100),
    width: scale(100),
    justifyContent: "center",
    alignItems: "center",
    borderRadius: scale(10),
    backgroundColor: COLORS.RED,
    marginLeft: scale(10),
  },
  classTitle: {
    fontFamily: FONTS.POPPINS_REGULAR,
    fontSize: scale(11.5),
    color: COLORS.BLACK,
    alignSelf: "center",
    marginLeft: scale(10),
    // paddingRight: scale(10),
    // paddingLeft: scale(10),
    marginTop: scale(5),
    textAlign: "center",
  },
  viewClassTitle: {
    fontFamily: FONTS.POPPINS_MEDIUM,
    fontSize: scale(13),
    color: COLORS.WHITE,
    alignSelf: "center",
    paddingRight: scale(10),
    paddingLeft: scale(10),
  },
});
export default styles;
