export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";

export const LOADER = "LOADER";

export const ALERT_REQUEST = "ALERT_REQUEST";
export const ALERT_RESPONSE = "ALERT_RESPONSE";

export const DASHBOARD_REQUEST = "DASHBOARD_REQUEST";
export const DASHBOARD_RESPONSE = "DASHBOARD_RESPONSE";

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_RESPONSE = "GET_CATEGORY_RESPONSE";

export const GET_COMPLAINT_REQUEST = "GET_COMPLAINT_REQUEST";
export const GET_COMPLAINT_RESPONSE = "GET_COMPLAINT_RESPONSE";

export const GET_BOOK_WISHLIST_REQUEST = "GET_BOOK_WISHLIST_REQUEST";
export const GET_BOOK_WISHLIST_RESPONSE = "GET_BOOK_WISHLIST_RESPONSE";

export const GET_FACILITY_REQUEST = "GET_FACILITY_REQUEST";
export const GET_FACILITY_RESPONSE = "GET_FACILITY_RESPONSE";

export const ADD_MASSAGE_REQUEST = "ADD_MASSAGE_REQUEST";
export const ADD_MASSAGE_RESPONSE = "ADD_MASSAGE_RESPONSE";

export const GET_DEPARTMENT_REQUEST = "GET_DEPARTMENT_REQUEST";
export const GET_DEPARTMENT_RESPONSE = "GET_DEPARTMENT_RESPONSE";

export const GET_RESTAURANT_LIST_REQUEST = "GET_RESTAURANT_LIST_REQUEST";
export const GET_RESTAURANT_LIST_RESPONSE = "GET_RESTAURANT_LIST_RESPONSE";

export const CLASS_LIST_REQUEST = "GET_CATEGORY_REQUEST";
export const CLASS_LIST_RESPONSE = "GET_CATEGORY_RESPONSE";

export const GET_SETTING_LIST_REQUEST = "GET_SETTING_LIST_REQUEST";
export const GET_SETTING_LIST_RESPONSE = "GET_SETTING_LIST_RESPONSE";

export const GET_OTTERITE_REQUEST = "GET_OTTERITE_REQUEST";
export const GET_OTTERITE_RESPONSE = "GET_OTTERITE_RESPONSE";

export const GET_EVENT_LIST_REQUEST = "GET_EVENT_LIST_REQUEST";
export const GET_EVENT_LIST_RESPONSE = "GET_EVENT_LIST_RESPONSE";

export const GET_OFFER_LIST_REQUEST = "GET_OFFER_LIST_REQUEST";
export const GET_OFFER_LIST_RESPONSE = "GET_OFFER_LIST_RESPONSE";

export const GET_MASSAGE_TIMESLOT_LIST_REQUEST = "GET_MASSAGE_TIMESLOT_LIST_REQUEST";
export const GET_MASSAGE_TIMESLOT_LIST_RESPONSE = "GET_MASSAGE_TIMESLOT_LIST_RESPONSE";

export const ADD_EDIT_COMPLAINT_LIST_REQUEST = "ADD_EDIT_COMPLAINT_LIST_REQUEST";
export const ADD_EDIT_COMPLAINT_LIST_RESPONSE = "ADD_EDIT_COMPLAINT_LIST_RESPONSE";

export const GET_BANQUET_INQUIRY_REQUEST = "GET_BANQUET_INQUIRY_REQUEST";
export const GET_BANQUET_INQUIRY_RESPONSE = "GET_BANQUET_INQUIRY_RESPONSE";