require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false
$RNFirebaseAsStaticFramework = true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'Firebase/Core'
pod 'Firebase/Messaging'

pod 'Firebase', :modular_headers => true
target 'JVPG_club' do
  config = use_native_modules!
  
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
# pod 'FirebaseCoreInternal', :modular_headers => true
# pod 'GoogleUtilities', :modular_headers => true
#   pod 'FirebaseCore', :modular_headers => true
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
  
   pod 'RNFBMessaging' ,:path => '../node_modules/@react-native-firebase/messaging'
 
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-view-shot', :path => '../node_modules/react-native-view-shot'

  pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

 
  pod 'RCTYouTube', :path => '../node_modules/react-native-youtube'

  pod 'react-native-create-thumbnail', :path => '../node_modules/react-native-create-thumbnail'

  target 'JVPG_clubTests' do
    inherit! :complete
    # Pods for testing
  end
#  target 'NotificationServiceExtension' do
#      pod 'Firebase/Messaging', '~> 10.3.0'
#  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
       end
    end
  end
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
#  use_flipper!()
#   use_flipper!
#   post_install do |installer|
#     flipper_post_install(installer)
#   end
#  post_install do |installer|
#    react_native_post_install(installer)
#    __apply_Xcode_12_5_M1_post_install_workaround(installer)
#  end

end

target 'ImageNotification' do
  pod 'Firebase/Messaging', '~> 10.3.0' # eg 6.31.0
end


