export const FONTS = {
  POPPINS_BLACK: "Poppins-Black",
  POPPINS_BOLD: "Poppins-Bold",
  POPPINS_EXTRA_BOLD: "Poppins-ExtraBold",
  POPPINS_REGULAR: "Poppins-Regular",
  POPPINS_SEMI_BOLD: "Poppins-SemiBold",
  POPPINS_MEDIUM: "Poppins-Medium",
  PLAYFAIR_DISPLAY_BOLD: "PlayfairDisplay-Bold",
  PLAYFAIR_DISPLAY_BLACK: "PlayfairDisplay-Black",
  PLAYFAIR_DISPLAY_BLACKITALIC: "PlayfairDisplay-BlackItalic",
  PLAYFAIR_DISPLAY_BOLDITALIC: "PlayfairDisplay-BoldItalic",
  PLAYFAIR_DISPLAY_EXTRABOLD: "PlayfairDisplay-ExtraBold",
  PLAYFAIR_DISPLAY_EXTRABOLDITALIC: "PlayfairDisplay-ExtraBoldItalic",
  PLAYFAIR_DISPLAY_ITALIC: "PlayfairDisplay-Italic",
  PLAYFAIR_DISPLAY_MEDIUM: "PlayfairDisplay-Medium",
  PLAYFAIR_DISPLAY_MEDIUMITALIC: "PlayfairDisplay-MediumItalic",
  PLAYFAIR_DISPLAY_REGULAR: "PlayfairDisplay-Regular",
  PLAYFAIR_DISPLAY_SEMIBOLD: "PlayfairDisplay-SemiBold",
  PLAYFAIR_DISPLAY_SEMIBOLDITALIC: "PlayfairDisplay-SemiBoldItalic",
  LORA_BOLD: "Lora-Bold",
  LORA_BOLDITALIC: "Lora-BoldItalic",
  LORA_ITALIC: "Lora-Italic",
  LORA_MEDIUM: "Lora-Medium",
  LORA_MEDIUMITALIC: "Lora-MediumItalic",
  LORA_REGULAR: "Lora-Regular",
  LORA_SEMIBOLD: "Lora-SemiBold",
  LORA_SEMIBOLDITALIC: "Lora-SemiBoldItalic",
};
