export const IMAGES = {
  ONBOARDING1: require("../../Assets/OnBoarding/onBoarding1.jpg"),
  ONBOARDING2: require("../../Assets/OnBoarding/onBoarding2.jpg"),
  ONBOARDING3: require("../../Assets/OnBoarding/onBoarding3.jpg"),
  NEXT_ARROW: require("../../Assets/Icons/next_arrow.png"),
  MAIN_LOGO: require("../../Assets/Icons/logo.png"),
  APP_LOGO: require("../../Assets/Icons/applogo.png"),
  USER: require("../../Assets/Icons/man.png"),
  HIDE_EYE: require("../../Assets/Icons/eyes.png"),
  SHOW_EYE: require("../../Assets/Icons/witness.png"),
  HOME: require("../../Assets/Icons/home.png"),
  HOME_FILL: require("../../Assets/Icons/home-hover.png"),
  EVENT: require("../../Assets/Icons/day_date.png"),
  EVENT_FILL: require("../../Assets/Icons/event_fill.png"),
  BOOK: require("../../Assets/Icons/open-book.png"),
  BOOKFILL: require("../../Assets/Icons/book_hover.png"),
  BILLING: require("../../Assets/Icons/billing.png"),
  BILLING_FILL: require("../../Assets/Icons/billing_hover.png"),
  QRCODE: require("../../Assets/Icons/qr_code.png"),
  QRCODE_FILL: require("../../Assets/Icons/qr_code-hover.png"),
  ALERT: require("../../Assets/Icons/alerts.png"),
  ALERT_FILL: require("../../Assets/Icons/updates_hover.png"),
  MORE: require("../../Assets/Icons/more-button-whit.png"),
  VIEW_ARROW: require("../../Assets/Icons/arrow.png"),
  BACK_ICON: require("../../Assets/Icons/back_arrow_white.png"),
  UNBILLED: require("../../Assets/Icons/unbilled_amount.png"),
  PAST_BILLS: require("../../Assets/Icons/past_bill.png"),
  PAYMENT_HISTORY: require("../../Assets/Icons/rupee.png"),
  VIEW_LEDGER: require("../../Assets/Icons/day_date.png"),
  MAKE_PAYMENT: require("../../Assets/Icons/makepaymen.png"),
  DOWNLOAD_BILL: require("../../Assets/Icons/downArrow.png"),
  DOWN_ARROW: require("../../Assets/Icons/down_arrow.png"),
  SUCCESS_WRITE: require("../../Assets/Icons/successful.png"),
  PLUS: require("../../Assets/Icons/add.png"),
  WRITE: require("../../Assets/Icons/checkbox.png"),
  REFRESH: require("../../Assets/Icons/refresh.png"),
  PAST_BOOKING: require("../../Assets/Icons/pastBooking.png"),
  SQUASH: require("../../Assets/Book/squashImg.jpeg"),
  EVENT_IMG: require("../../Assets/Book/event_image.jpeg"),
  MASSAGE: require("../../Assets/Book/MassageImg.png"),
  BANQUET: require("../../Assets/Book/banquet.jpeg"),
  BADMINTON: require("../../Assets/Book/badminton.jpeg"),
  LAWN_TENNIS: require("../../Assets/Book/lawnTennis.webp"),
  BANQUET1: require("../../Assets/Banquet/banquethall1.jpeg"),
  BANQUET2: require("../../Assets/Banquet/banquethall2.jpeg"),
  BANQUET3: require("../../Assets/Banquet/banquethall3.jpeg"),
  BANQUET4: require("../../Assets/Banquet/banquethall4.jpeg"),
  CLOSE: require("../../Assets/Icons/close_button.png"),
  BLANK_BOX: require("../../Assets/Icons/blank_box.png"),
  MINUS: require("../../Assets/Icons/subtract.png"),
  EYE: require("../../Assets/Icons/view.png"),
  SEARCH:require("../../Assets/Icons/search_icon.png"),
  BOOK_AVAILABLE:require("../../Assets/Icons/available.png"),
  WISHLIST:require("../../Assets/Icons/wishlist.png"),
  BOOK_BORROWED:require("../../Assets/Icons/book-allowed.png"),
  EDIT:require("../../Assets/Icons/edit_blue.png"),
  BOOKING_BACKGROUND:require("../../Assets/Icons/coupon_back.png"),
  TIME:require("../../Assets/Icons/time.png"),
  LOCATION:require("../../Assets/Icons/location.png"),
  NOTIFICATION:require("../../Assets/Icons/notification.png"),
  CHANGE_PASSWORD:require("../../Assets/Icons/changepasword.png"),
  LOGOUT:require("../../Assets/Icons/logout.png"),
  MEMBER:require("../../Assets/Icons/member.png"),
  MY_BOOKING:require("../../Assets/Icons/mybooking.png"),
  UPDATE:require("../../Assets/Icons/updatedetail.png"),
  CAMERA: require("../../Assets/Icons/camera.png"),
  DIRECTORY: require("../../Assets/Icons/folder.png"),
  MINUS_BOOK: require("../../Assets/Icons/minus.png"),
  PLUS_BOOK: require("../../Assets/Icons/plus.png"),
};
