export const SCREENS = {
  ONBOARDING: "OnBoarding",
  LOGIN: "Login",
  BOTTOM_TAB_NAVIGATOR: "TabNavigation",
  HOME: "Home",
  BOOK_TAB: "BookTab",
  BOOK: "Book",
  BILLING_TAB: "BillingTab",
  MENU: "Menu",
  UPDATES: "Updates",
  DRAWER_NAVIGATION: "DrawerNavigation",
  AUTH_NAVIGATOR: "AuthNavigation",
  STACK_NAVIGATOR: "StackNavigation",
  DASHBOARD: "Dashboard",
  PROFILE: "ProfileScreen",
  REGISTER_GUEST: "RegisterGuest",
  VIEW_GUEST_QR: "ViewGuestQr",
  NEWS_SUB_SCREEN: "NewsScreen",
  NEWS_DETAIL_SCREEN: "NewsDetail",
  OFFER_SUB_SCREEN: "OfferScreen",
  OFFER_DETAIL_SCREEN: "OfferDetailScreen",
  BILLING: "Billing",
  PAST_BILLS: "PastBills",
  PAYMENT_HISTORY: "PaymentHistory",
  UNBILLED_AMOUNT: "UnbilledAmount",
  VIEW_LEDGER: "ViewLedger",
  MAKE_PAYMENT: "MakePayment",
  RAISE_ISSUE: "RaiseIssue",
  RAIS_ISSUE_SUCCESS: "RaiseIssueSuccess",
  VIEW_COMPLAINT: "ViewComplaint",
  ADD_COMPLAINT: "AddComplaint",
  COMPLAINT_SUCCESS: "ComplaintSuccess",
  PAYMENT_SUCCESS: "PaymentSuccess",
  FAVOURITE: "FavouriteScreen",
  CLASSES: "Classes",
  BANQUET: "Banquet",
  BANQUET_BOOKING: "BanquetBooking",
  BANQUET_SUCEESS: "BanquetSuccess",
  MASSAGE_SCREEN: "MassageScreen",
  EVENTS: "Events",
  EVENT_DETAIL: "EventDetail",
  BOOKING_DETAIL: "BookingDetail",
  SQUASH: "Squash",
  LIBRARY: "Library",
  EXPLORE_CATEGORIES: "ExploreCategories",
  BOOK_BORROWED: "BookBorrowed",
  LIBRARY_BOOK_LIST: "LibraryBookList",
  MY_WISHLIST: "MyWishlist",
  UPDATE_PROFILE: "UpdateProfile",
  FORGOT_PASSWORD: "ForgotPassword",
  OTP_SCREEN: "OtpScreen",
  NEW_PASSWOED: "NewPassword",
  REGISTER: "RegisterScreen",
  CHANGE_PASSWORD:"ChangePassword",
  FORGOT_SUCCESS:"RegisterSuccess",
  MASSAGE_DETAIL:"MassageDetail"

};
